'use client';
import { useState } from 'react';
import { MessageCircle } from 'lucide-react';
import { QUOTE_CATALOG, QUOTE_TAX_LABEL, QUOTE_WHATSAPP_NUMBER, formatEUR } from '@/lib/quotes/catalog';
import styles from '../quote.module.css';
export default function SeoHorasBlock() {
  const [hours, setHours] = useState(1);
  const total = hours * QUOTE_CATALOG.seoHour.amount;
  const message = `Hola, Latech. Ya tengo web y me gustaría revisar una propuesta de SEO: ${hours} ${hours === 1 ? 'hora' : 'horas'} × ${formatEUR(QUOTE_CATALOG.seoHour.amount)} = ${formatEUR(total)} de pago único. ${QUOTE_TAX_LABEL}. Quiero confirmar el alcance antes de contratar.`;
  return <section className="mt-16 border-t border-white/15 pt-10" aria-labelledby="seo-quote-title"><div className="grid gap-6 md:grid-cols-[1fr_auto]"><div><p className="text-xs uppercase tracking-widest text-amber-300">¿Ya tienes web?</p><h2 id="seo-quote-title" className="mt-3 font-display text-2xl font-bold text-white">También podemos trabajar su SEO.</h2><p className="mt-3 max-w-lg text-sm leading-relaxed text-white/65">Esta consulta es independiente del presupuesto de creación. Elige unas horas como referencia y definimos contigo qué conviene revisar.</p></div><div className="rounded-2xl border border-white/15 p-5"><label htmlFor="seo-hours" className="mb-2 block text-sm text-white/80">Horas de trabajo</label><div className="flex items-center gap-4"><input id="seo-hours" type="number" min={1} max={100} step={1} inputMode="numeric" className={`${styles.input} max-w-24 text-center font-mono`} value={hours} onChange={e => setHours(Math.min(100, Math.max(1, Math.floor(Number(e.target.value) || 1))))} /><p className="font-mono text-xl text-amber-300">{formatEUR(total)}</p></div><p className="mt-3 text-xs text-white/60">{formatEUR(QUOTE_CATALOG.seoHour.amount)}/hora · {QUOTE_TAX_LABEL}.</p><a href={`https://wa.me/${QUOTE_WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`} target="_blank" rel="noopener noreferrer" className={`${styles.button} mt-5 w-full text-sm`}><MessageCircle size={16} />Consultar SEO por WhatsApp</a><p className="mt-3 max-w-xs text-xs leading-relaxed text-white/50">Se abrirá un mensaje para que lo revises y lo envíes.</p></div></div></section>;
}
