'use client';
import Link from 'next/link';
import { useState, type ReactNode } from 'react';
import { ArrowUpRight, Check, Copy, MessageCircle, Pencil } from 'lucide-react';
import { QUOTE_CATALOG as PRICE, QUOTE_TAX_LABEL, formatEUR } from '@/lib/quotes/catalog';
import { buildWhatsAppMessage, buildWhatsAppUrl, contactErrors, type ContactState, type WizardState, type WizardAction, type Cart } from '../_lib/state';
import { OptionCard, StepHeader, ToggleGroup } from './StepShell';
import Summary from './Summary';
import styles from '../quote.module.css';

type StepProps = { state: WizardState; dispatch: (action: WizardAction) => void };
function Choice({ title, children, price }: { title: string; children: ReactNode; price?: string }) {
  return <><p className={styles.optionTitle}>{title}</p><p className="mt-2 text-sm leading-relaxed text-white/60">{children}</p>{price && <p className="mt-4 font-mono text-sm text-amber-300">{price}</p>}</>;
}
export function StepProject({ state, dispatch }: StepProps) {
  return <><StepHeader title="Empecemos por tu web." subtitle="Una base de 600 € de creación, adaptada a tu marca. Cuéntanos el tamaño y si necesitas vender online." />
    <div className="space-y-8"><ToggleGroup label="¿Cuántas páginas necesitas?"><OptionCard selected={!state.webPagesOver8} onClick={() => dispatch({ type: 'SET_WEB_OVER8', value: false })} ariaLabel="Hasta 8 páginas"><Choice title="Hasta 8 páginas" price={`${formatEUR(PRICE.creation.amount)} de creación`}>Inicio, servicios, equipo, contacto… Las secciones que tu negocio necesita.</Choice></OptionCard><OptionCard selected={state.webPagesOver8} onClick={() => dispatch({ type: 'SET_WEB_OVER8', value: true })} ariaLabel="Más de 8 páginas"><Choice title="Más de 8 páginas" price={`Base de ${formatEUR(PRICE.creation.amount)}`}>Un proyecto más amplio. Revisaremos la estructura y cualquier trabajo adicional contigo.</Choice></OptionCard></ToggleGroup>
    <ToggleGroup label="¿Vas a vender desde la web?"><OptionCard selected={!state.tienda} onClick={() => dispatch({ type: 'SET_TIENDA', value: false })} ariaLabel="Web sin tienda"><Choice title="Mostrar y captar" price={`${formatEUR(PRICE.maintenance.amount)}/mes de mantenimiento`}>Una web para presentar tu negocio y recibir consultas.</Choice></OptionCard><OptionCard selected={state.tienda} onClick={() => dispatch({ type: 'SET_TIENDA', value: true })} ariaLabel="Web con tienda online"><Choice title="Vender online" price={`${formatEUR(PRICE.maintenance.amount + PRICE.shop.amount)}/mes de mantenimiento`}>Catálogo, carrito y pasarela de pago. Incluye el mantenimiento base y el de la tienda.</Choice></OptionCard></ToggleGroup></div>
    <p className="mt-6 text-xs leading-relaxed text-white/55">{QUOTE_TAX_LABEL}. La creación parte de la misma base; confirmaremos el alcance antes de cerrar el presupuesto.</p></>;
}
export function StepServices({ state, dispatch }: StepProps) {
  return <><StepHeader title="Tu equipo, con más alcance." subtitle="El hosting y el mantenimiento ya están incluidos en tu cuota. Añade ayuda con las redes o la atención al cliente si la necesitas." />
    <div className="mb-7 flex items-start gap-3 rounded-xl border border-white/10 p-4 text-sm text-white/75"><Check size={18} className="mt-0.5 shrink-0 text-amber-300" /><p>Hosting, SSL, mantenimiento y cambios menores: <strong className="text-white">{formatEUR(PRICE.maintenance.amount)}/mes</strong>{state.tienda && <>; tienda online: <strong className="text-white">+{formatEUR(PRICE.shop.amount)}/mes</strong></>}. Ya están en tu resumen.</p></div>
    <div className="space-y-8"><ToggleGroup label="Redes sociales"><OptionCard selected={!state.social} onClick={() => dispatch({ type: 'SET_SOCIAL', value: false })} ariaLabel="Sin gestión de redes"><Choice title="Me encargo yo">Mantengo la gestión de mis cuentas.</Choice></OptionCard><OptionCard selected={state.social} onClick={() => dispatch({ type: 'SET_SOCIAL', value: true })} ariaLabel="Añadir gestión de redes"><Choice title="Con ayuda de Latech" price={`+${formatEUR(PRICE.social.amount)}/mes`}>Gestión de redes y 2–3 publicaciones semanales.</Choice></OptionCard></ToggleGroup>
    <ToggleGroup label="Agente de inteligencia artificial" columns={3}><OptionCard selected={state.aiAgent === 'none'} onClick={() => dispatch({ type: 'SET_AI', value: 'none' })} ariaLabel="Sin agente IA"><Choice title="Por ahora, no">Mi equipo atiende las consultas.</Choice></OptionCard><OptionCard selected={state.aiAgent === 'web'} onClick={() => dispatch({ type: 'SET_AI', value: 'web' })} ariaLabel="Agente IA en la web"><Choice title="En mi web" price={`+${formatEUR(PRICE.aiWeb.amount)}/mes`}>Atención conversacional integrada en tu página.</Choice></OptionCard><OptionCard selected={state.aiAgent === 'phone'} onClick={() => dispatch({ type: 'SET_AI', value: 'phone' })} ariaLabel="Agente IA por teléfono"><Choice title="Por teléfono" price={`+${formatEUR(PRICE.aiPhone.amount)}/mes`}>Atención por voz con número virtual. Definimos la integración contigo.</Choice></OptionCard></ToggleGroup></div>
    <Link href="/tienda/agente-ia" target="_blank" rel="noreferrer" className={`${styles.textButton} mt-4 inline-flex items-center gap-2 text-sm`}>Conoce las opciones de IA <ArrowUpRight size={14} /></Link><p className="mt-2 text-xs text-white/55">{QUOTE_TAX_LABEL}. Los requisitos de una integración a medida se revisan antes de contratar.</p></>;
}
export function StepContent({ state, dispatch }: StepProps) {
  return <><StepHeader title="Contenido con tu identidad." subtitle="La estructura del blog está incluida. Puedes gestionar tus artículos o añadir redacción y un logo a tu presupuesto." />
    <div className="mb-8 rounded-2xl border border-white/15 p-5"><label htmlFor="blog-posts" className="block font-semibold text-white">Artículos gestionados al mes</label><p id="blog-posts-hint" className="mt-2 text-sm leading-relaxed text-white/65">Elige entre 0 y 100. Con 0, publicas por tu cuenta. Definimos los temas según tu negocio, sin prometer posiciones en Google.</p><div className="mt-5 flex flex-wrap items-center gap-4"><input id="blog-posts" className={`${styles.input} max-w-28 text-center font-mono`} type="number" min={0} max={100} step={1} inputMode="numeric" value={state.blogPosts} onChange={e => dispatch({ type: 'SET_BLOG_POSTS', value: Number(e.target.value) })} aria-describedby="blog-posts-hint blog-posts-price" /><p id="blog-posts-price" className="text-sm text-white/75">{state.blogPosts > 0 ? <>{state.blogPosts} × {formatEUR(PRICE.blogPost.amount)} = <strong className="font-mono text-amber-300">{formatEUR(state.blogPosts * PRICE.blogPost.amount)}/mes</strong></> : 'Sin redacción añadida a la cuota.'}</p></div></div>
    <ToggleGroup label="¿Necesitas un logo?"><OptionCard selected={!state.logo} onClick={() => dispatch({ type: 'SET_LOGO', value: false })} ariaLabel="Sin diseño de logo"><Choice title="Ya tengo mi identidad">Trabajamos con el logo de tu marca.</Choice></OptionCard><OptionCard selected={state.logo} onClick={() => dispatch({ type: 'SET_LOGO', value: true })} ariaLabel="Añadir diseño de logo"><Choice title="Quiero un logo" price={`+${formatEUR(PRICE.logo.amount)} · pago único`}>Añadimos el diseño de logo al proyecto.</Choice></OptionCard></ToggleGroup><p className="mt-6 text-xs text-white/55">{QUOTE_TAX_LABEL} en todos los extras.</p></>;
}
export function StepContact({ state, dispatch }: StepProps) {
  const c = state.contact; const errors = contactErrors(c); const [touched, setTouched] = useState<Record<string, boolean>>({});
  const set = (patch: Partial<ContactState>) => dispatch({ type: 'SET_CONTACT', patch });
  const fields = [
    { key: 'name', label: 'Tu nombre', type: 'text', autoComplete: 'name', max: 100 },
    { key: 'company', label: 'Tu negocio', type: 'text', autoComplete: 'organization', max: 120 },
    { key: 'email', label: 'Email', type: 'email', autoComplete: 'email', max: 180 },
    { key: 'phone', label: 'Teléfono', type: 'tel', autoComplete: 'tel', max: 32 },
  ] as const;
  return <><StepHeader title="Ponle contexto a tu idea." subtitle="Todos estos datos son opcionales. Puedes pasar directamente al resumen y hablar con nosotros desde tu WhatsApp." /><div className="grid gap-5 sm:grid-cols-2">{fields.map(field => <div key={field.key}><label htmlFor={`quote-${field.key}`} className="mb-2 block text-sm text-white/80">{field.label} <span className="text-xs text-white/45">(opcional)</span></label><input id={`quote-${field.key}`} className={styles.input} type={field.type} value={c[field.key]} autoComplete={field.autoComplete} maxLength={field.max} onChange={e => set({ [field.key]: e.target.value })} onBlur={() => setTouched(prev => ({ ...prev, [field.key]: true }))} aria-invalid={Boolean(touched[field.key] && errors[field.key])} aria-describedby={touched[field.key] && errors[field.key] ? `quote-${field.key}-error` : undefined} />{touched[field.key] && errors[field.key] && <p id={`quote-${field.key}-error`} className="mt-2 text-xs text-rose-300">{errors[field.key]}</p>}</div>)}</div><label htmlFor="quote-notes" className="mt-6 mb-2 block text-sm text-white/80">¿Qué te gustaría conseguir? <span className="text-xs text-white/45">(opcional)</span></label><textarea id="quote-notes" rows={4} className={styles.input} maxLength={600} value={c.notes} onChange={e => set({ notes: e.target.value })} placeholder="A qué te dedicas, tu web actual, una fecha importante o una idea que quieras contarnos…" aria-describedby="quote-notes-hint" /><p id="quote-notes-hint" className="mt-2 text-right text-xs text-white/45">{c.notes.length}/600</p><p className="mt-6 text-xs leading-relaxed text-white/60">Tus datos se añadirán al mensaje que tú envíes por WhatsApp. No se guardan en este navegador al recargar. Consulta nuestra <Link href="/privacidad" className="text-white underline underline-offset-4">política de privacidad</Link>.</p></>;
}
export function StepReview({ state, cart, onEdit }: { state: WizardState; cart: Cart; onEdit: (step: number) => void }) {
  const [notice, setNotice] = useState(''); const [showMessage, setShowMessage] = useState(false);
  const message = buildWhatsAppMessage(state);
  const rows = [
    { title: 'Proyecto', text: `${state.webPagesOver8 ? 'Más de 8 páginas · alcance por revisar' : 'Hasta 8 páginas'} · ${state.tienda ? 'con tienda online' : 'sin tienda online'}`, step: 1 },
    { title: 'Servicios', text: `Mantenimiento mensual · ${state.social ? 'con redes' : 'sin redes'} · ${state.aiAgent === 'none' ? 'sin agente IA' : state.aiAgent === 'web' ? 'IA en la web' : 'IA por teléfono'}`, step: 2 },
    { title: 'Contenido', text: `${state.blogPosts} artículos al mes · ${state.logo ? 'con diseño de logo' : 'sin diseño de logo'}`, step: 3 },
    { title: 'Tu contexto', text: [state.contact.name, state.contact.company, state.contact.email, state.contact.phone, state.contact.notes].filter(Boolean).join(' · ') || 'Sin datos añadidos. Puedes contárnoslo por WhatsApp.', step: 4 },
  ];
  const copyMessage = async () => {
    try { await navigator.clipboard.writeText(message); setNotice('Mensaje copiado. Puedes pegarlo en WhatsApp.'); }
    catch { setShowMessage(true); setNotice('Selecciona y copia el mensaje de abajo.'); }
  };
  return <><StepHeader title="Tu idea ya tiene números." subtitle="Revisa cada elección. Abriremos WhatsApp con el presupuesto preparado; allí podrás editar el mensaje y enviarlo tú." /><div className="mb-7">{rows.map(row => <div key={row.title} className={styles.reviewRow}><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wider text-white/50">{row.title}</p><p className="mt-2 break-words text-sm leading-relaxed text-white/85">{row.text}</p></div><button type="button" onClick={() => onEdit(row.step)} className={`${styles.textButton} self-start text-xs`} aria-label={`Editar ${row.title.toLowerCase()}`}><Pencil size={14} aria-hidden="true" /><span className="sr-only">Editar</span></button></div>)}</div><div className="lg:hidden"><Summary cart={cart} /></div><div className="mt-7 space-y-4"><a href={buildWhatsAppUrl(state)} target="_blank" rel="noopener noreferrer" className={`${styles.button} ${styles.primary} w-full text-center text-sm sm:text-base`}><MessageCircle size={20} className="shrink-0" />Enviar presupuesto por WhatsApp</a><p className="text-xs leading-relaxed text-white/60">Abrir WhatsApp no envía el mensaje automáticamente ni contrata ningún servicio. Confirmaremos el presupuesto contigo.</p><div className="flex flex-wrap gap-x-6 gap-y-1"><button type="button" className={`${styles.textButton} inline-flex items-center gap-2 text-sm`} onClick={copyMessage}><Copy size={14} />Copiar mensaje</button><button type="button" className={`${styles.textButton} text-sm`} onClick={() => setShowMessage(v => !v)} aria-expanded={showMessage} aria-controls="quote-message">{showMessage ? 'Ocultar mensaje' : 'Ver mensaje completo'}</button></div><p className="text-xs text-amber-200" role="status">{notice}</p>{showMessage && <div id="quote-message"><label htmlFor="quote-message-text" className="mb-2 block text-xs text-white/65">Este es el mensaje que se abrirá en WhatsApp</label><textarea id="quote-message-text" readOnly value={message} className={`${styles.input} ${styles.message}`} onFocus={e => e.target.select()} /></div>}</div></>;
}
