'use client';
import {useRef,type PointerEvent} from 'react';
import type {ArcadeMode} from '@/lib/arcade-protocol';
import styles from './Arcade.module.css';
type Props={mode:ArcadeMode;disabled:boolean;setInput:(bit:number,pressed:boolean)=>void;setLook:(x:number,y:number)=>void};
export default function ArcadeLiveControls({mode,disabled,setInput,setLook}:Props){
  const pointer=useRef<{id:number;x:number;y:number}|null>(null);
  const bind=(bit:number)=>({onPointerDown:(e:PointerEvent<HTMLButtonElement>)=>{if(disabled)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);setInput(bit,true);if('vibrate'in navigator)navigator.vibrate(8);},onPointerUp:()=>setInput(bit,false),onPointerCancel:()=>setInput(bit,false),onLostPointerCapture:()=>setInput(bit,false),onContextMenu:(e:React.MouseEvent)=>e.preventDefault()});
  const lookDown=(e:PointerEvent<HTMLDivElement>)=>{if(disabled||pointer.current)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);pointer.current={id:e.pointerId,x:e.clientX,y:e.clientY};};
  const lookMove=(e:PointerEvent<HTMLDivElement>)=>{const p=pointer.current;if(p?.id===e.pointerId)setLook((e.clientX-p.x)/55,(e.clientY-p.y)/55);};
  const lookUp=()=>{pointer.current=null;setLook(0,0);};
  const live=['platform','fight','blocks'].includes(mode);const off=disabled||!live;
  if(mode==='blocks')return <><div className={styles.blockPadArea}><div className={styles.fullDpad}>{[[128,'↑','Avanzar'],[1,'←','Izquierda'],[2,'→','Derecha'],[256,'↓','Retroceder']].map(([bit,label,name])=><button key={bit} className={styles.padButton} disabled={off} aria-label={String(name)} {...bind(Number(bit))}>{label}</button>)}</div><div className={styles.lookPad} role="group" aria-label="Desliza para mirar alrededor" onPointerDown={lookDown} onPointerMove={lookMove} onPointerUp={lookUp} onPointerCancel={lookUp} onLostPointerCapture={lookUp}><span>✛</span><small>MIRAR</small></div></div><div className={styles.builderButtons}>{[[8,'Romper'],[16,'Colocar'],[4,'Saltar / subir'],[32,'Material'],[64,'Volar / caer']].map(([bit,label])=><button key={bit} className={styles.padButton} disabled={off} {...bind(Number(bit))}>{label}</button>)}</div><p className={styles.padCaption}>CRUCETA · CAMINAR / ZONA DERECHA · MIRAR<br/>Mantén romper o colocar para construir seguido.</p></>;
  return <><div className={styles.padArea}><div className={styles.dpad}><button className={styles.padButton} {...bind(1)} aria-label="Mover a la izquierda" disabled={off}>◀</button><button className={styles.padButton} {...bind(2)} aria-label="Mover a la derecha" disabled={off}>▶</button>{mode==='fight'&&<button className={`${styles.padButton} ${styles.padJump}`} {...bind(4)} aria-label="Saltar" disabled={off}>▲</button>}</div>{mode==='fight'?<div className={styles.fightButtons}>{[[8,'Puño'],[16,'Patada'],[32,'Bloqueo'],[64,'Especial']].map(([bit,label])=><button key={bit} className={styles.padButton} disabled={off} {...bind(Number(bit))}>{label}</button>)}</div>:<div className={styles.ab}><button className={styles.padButton} {...bind(8)} aria-label="Correr" disabled={off}>B</button><button className={styles.padButton} {...bind(4)} aria-label="Saltar" disabled={off}>A</button></div>}</div><p className={styles.padCaption}>{mode==='fight'?'PULSA PUÑO O PATADA · MANTÉN BLOQUEO · ESPECIAL CON ENERGÍA':'CRUCETA · MOVER / B · CORRER / A · SALTAR'}<br/>{mode==='fight'?'La flecha superior salta. Gana dos rondas.':'Pulsa A de nuevo en el aire para un doble salto. Ambos jugadores comparten vidas.'}</p></>;
}
