'use client';
import { useEffect, useRef, useState } from 'react';
import { playArcadeSound } from '@/lib/arcade-audio';
import type { ArcadeView, Player } from '@/lib/arcade-engine';
import styles from './Arcade.module.css';
const coordinate = (cell: number, columns = 8) => `${String.fromCharCode(65 + Math.floor(cell / columns))}${cell % columns + 1}`;
export default function ArcadeBoard({ game, player = null, onMove, busy = false }: { game: ArcadeView; player?: Player | null; onMove?: (cell: number) => void; busy?: boolean }) {
  const [hovered, setHovered] = useState<number | null>(null);
  const previous = useRef({ kind: game.kind, moves: game.moves });
  useEffect(() => {
    if (previous.current.kind === game.kind && game.moves > previous.current.moves) playArcadeSound(game.winner !== null ? 'finish' : game.kind === 'naval' ? game.boards[game.turn][game.last] === 2 ? 'hit' : 'scan' : game.kind === 'space' ? 'hit' : 'coin');
    previous.current = { kind: game.kind, moves: game.moves };
  }, [game]);
  const landing = game.kind === 'orbit' && hovered !== null ? [5,4,3,2,1,0].map(row => row * 7 + hovered).find(cell => game.grid[cell] === -1) : undefined;
  const canPlay = player !== null && player === game.turn && game.winner === null && !busy;
  const lastShot = (cell: number, owner?: Player) => game.moves > 0 && game.last === cell && (owner === undefined || owner === game.turn);
  return <section className={styles.game} data-game={game.kind} aria-label={game.kind === 'naval' ? 'Batalla naval' : game.kind === 'space' ? 'Space Wars' : 'Cuatro en órbita'}>
    <div className={styles.hud}><h2>{game.kind === 'naval' ? 'Mar abierto.' : game.kind === 'space' ? 'Space Wars.' : 'Cuatro en órbita.'}</h2><div className={styles.status}>{game.kind === 'space' ? `MISIÓN ${String(game.level).padStart(2, '0')} / 10 · BLINDAJE ${game.hull}/10` : `TURNO ${game.moves + 1}`}<br />{game.winner !== null ? 'PARTIDA TERMINADA' : `JUGADOR ${game.turn + 1} · ${player === null ? 'ELIGE EN TU MANDO' : canPlay ? 'TE TOCA' : 'ESPERA TU TURNO'}`}</div></div>
    {game.kind === 'naval' && <div className={styles.boardPair}>{([0, 1] as Player[]).filter(owner => player === null || owner !== player).map(owner => <div key={owner}><p className={styles.boardTitle}>{player === null ? `SECTOR DEL JUGADOR ${owner + 1}` : 'RADAR RIVAL · TOCA PARA DISPARAR'}</p><div className={styles.board}>{game.boards[owner].map((value, cell) => player !== null ? <button key={cell} className={styles.cell} data-state={value} data-last={lastShot(cell, owner)} disabled={!canPlay || value === 1 || value === 2} onClick={() => onMove?.(cell)} aria-label={`${coordinate(cell)}: ${value === 1 ? 'agua' : value === 2 ? 'impacto' : 'disparar'}`}><small aria-hidden>{coordinate(cell)}</small></button> : <div key={cell} className={styles.cell} data-state={value} data-last={lastShot(cell, owner)}><small>{coordinate(cell)}</small></div>)}</div></div>)}</div>}
    {game.kind === 'space' && <><div className={`${styles.board} ${styles.spaceBoard}`}>{Array.from({ length: 40 }, (_, cell) => { const enemy = game.enemies.find(item => item.cell === cell); return <button key={cell} className={styles.cell} data-last={lastShot(cell)} disabled={!canPlay || !enemy} onClick={() => onMove?.(cell)} aria-label={`${coordinate(cell)}: ${enemy ? `nave, ${enemy.hp} de resistencia` : 'espacio vacío'}`}><small aria-hidden>{coordinate(cell)}</small>{enemy && <><span className={styles.sprite} data-armored={enemy.hp > 1} data-boss={enemy.hp > 2} aria-hidden /><b className={styles.enemyHp} aria-hidden>{enemy.hp > 1 ? "◆".repeat(enemy.hp) : ""}</b></>}</button>; })}</div>{player !== null && <div className={styles.padActions}><button className={styles.button} disabled={!canPlay || game.charge[player] >= 2} onClick={() => onMove?.(-1)}>Cargar disparo · {game.charge[player]}/2</button></div>}</>}
    {game.kind === 'orbit' && <>{player !== null && <div className={styles.orbitColumns}>{Array.from({ length: 7 }, (_, column) => <button className={styles.button} key={column} disabled={!canPlay || game.grid[column] !== -1} onClick={() => onMove?.(column)} onPointerEnter={() => setHovered(column)} onPointerLeave={() => setHovered(null)} onFocus={() => setHovered(column)} onBlur={() => setHovered(null)} aria-label={`Soltar ficha en columna ${column + 1}`}>↓</button>)}</div>}<div className={styles.orbitBoard}>{game.grid.map((value, cell) => <div key={cell} className={styles.orbitDisc} data-player={value} data-last={lastShot(cell)} data-winning={game.winning.includes(cell)} data-preview={canPlay && landing === cell} aria-label={value < 0 ? 'Vacío' : `Jugador ${value + 1}`} />)}</div></>}
    <div className={styles.tacticalInfo}>
      {game.kind === 'naval' ? <><span>J1 · {game.boards[1].filter(v=>v===2).length}/14 IMPACTOS</span><span>J2 · {game.boards[0].filter(v=>v===2).length}/14 IMPACTOS</span></> : game.kind === 'space' ? <><span>J1 · {game.scores[0].toLocaleString('es-ES')} PTS · CARGA {game.charge[0]}/2</span><span>J2 · {game.scores[1].toLocaleString('es-ES')} PTS · CARGA {game.charge[1]}/2</span></> : <><span>J1 · {game.grid.filter(v=>v===0).length} FICHAS</span><span>J2 · {game.grid.filter(v=>v===1).length} FICHAS</span></>}
    </div>
    <p className={styles.tacticalRule}>{game.kind === 'naval' ? 'Cinco barcos por flota. Los impactos quedan marcados; tu flota solo se ve en tu mando.' : game.kind === 'space' ? 'Dos acciones antes de que avance la flota. Carga 2/2: explosión que alcanza objetivos adyacentes. Jefes en misiones 5 y 10.' : 'Conecta cuatro en horizontal, vertical o diagonal. La silueta indica dónde caerá tu ficha.'}</p>
    <p className={styles.message} role="status">{game.message}</p>
    {game.kind === 'naval' && player !== null && <details><summary className={styles.padCaption}>Ver mi flota · solo visible en tu mando</summary><div className={styles.board}>{game.boards[player].map((value, cell) => <div key={cell} className={styles.cell} data-state={value} aria-label={`${coordinate(cell)}: ${value === 3 ? 'barco propio' : value === 2 ? 'impacto' : value === 1 ? 'agua' : 'sin explorar'}`} />)}</div></details>}
  </section>;
}
