'use client';
import {useEffect,useRef,useState,type MutableRefObject} from 'react';
import * as THREE from 'three';
import {consumeInput,activeLook,type RemoteInput} from '@/lib/arcade-peer';
import {BLOCK_NAMES,BLOCK_COLORS,BLOCK_SAVE_VERSION,blockChunkGeometry,editFromBuilder,newBlockWorld,newBuilder,restoreBlockEdits,stepBuilder,lookBuilder,raycastBlocks} from '@/lib/blocks-engine';
import {createBlockAtmosphere,createBuilderAvatar} from '@/lib/blocks-scene';
import {playArcadeSound} from '@/lib/arcade-audio';
import styles from './Arcade.module.css';
import{arcadeFrameProbe,recordArcade}from'@/lib/arcade-diagnostics';
const SAVE='latech-isla-libre-v2';
export default function BlocksGame({remote,pauseSignal=0}:{remote:MutableRefObject<[RemoteInput,RemoteInput]>;pauseSignal?:number}){
  const canvas=useRef<HTMLCanvasElement>(null);const keys=useRef<[number,number]>([0,0]);const touch=useRef(0);const pause=useRef(false);
  const[loading,setLoading]=useState(true);const[progress,setProgress]=useState(0);const[error,setError]=useState('');const[paused,setPaused]=useState(false);const[materials,setMaterials]=useState([1,8]);const[coordinates,setCoordinates]=useState(['','']);const selections=useRef<[number|null,number|null]>([null,null]);const[saved,setSaved]=useState('Se guarda en este dispositivo');const[help,setHelp]=useState(true);const helpRef=useRef(true);
  useEffect(()=>{pause.current=paused;},[paused]);useEffect(()=>{helpRef.current=help;},[help]);
  const previousPause=useRef(pauseSignal);useEffect(()=>{if(previousPause.current!==pauseSignal)setPaused(true);previousPause.current=pauseSignal;},[pauseSignal]);
  useEffect(()=>{
    const element=canvas.current;if(!element)return;let renderer:THREE.WebGLRenderer;let cancelled=false;
    try{renderer=new THREE.WebGLRenderer({canvas:element,antialias:false,powerPreference:'low-power'});}catch{recordArcade('blocks:webgl-unavailable');queueMicrotask(()=>{if(!cancelled){setError('Este dispositivo no ha podido iniciar los gráficos 3D. Los juegos 2D siguen disponibles.');setLoading(false);}});return()=>{cancelled=true;};}
    let disposed=false,frame=0,last=performance.now(),accumulator=0,lastHud=0,saveTimer:ReturnType<typeof setTimeout>|undefined,prepareTimer:ReturnType<typeof setTimeout>|undefined,width=1,height=1,active=0;const probe=arcadeFrameProbe('blocks');
    const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
    const world=newBlockWorld();try{const raw=localStorage.getItem(SAVE);if(raw)restoreBlockEdits(world,raw);}catch{queueMicrotask(()=>{if(!disposed)setSaved('Guardado local no disponible');});}
    const players=[newBuilder(world,0),newBuilder(world,1)];const scene=new THREE.Scene();const atmosphere=createBlockAtmosphere(scene,world);
    renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setScissorTest(true);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;
    const cameras=[new THREE.PerspectiveCamera(72,1,.08,210),new THREE.PerspectiveCamera(72,1,.08,210)];cameras.forEach(c=>{c.rotation.order='YXZ';});
    const chunks=new Map<string,THREE.Mesh>();const material=new THREE.MeshLambertMaterial({vertexColors:true});
    const avatars=players.map((_,slot)=>{const avatar=createBuilderAvatar(slot);scene.add(avatar.group);return avatar;});
    const lamps=players.map(()=>{const light=new THREE.PointLight('#ffe2a7',8,10,1.4);scene.add(light);return light;});
    const outlines=[0,1].map(slot=>{const box=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(1.007,1.007,1.007)),new THREE.LineBasicMaterial({color:slot?'#ffbb63':'#ffffff'}));scene.add(box);return box;});
    function remesh(limit=Infinity){let count=0;for(const key of world.dirty){if(count++>=limit)break;const[cx,cz]=key.split(',').map(Number),data=blockChunkGeometry(world,cx,cz);const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(data.positions,3));geometry.setAttribute('normal',new THREE.Float32BufferAttribute(data.normals,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(data.colors,3));geometry.setAttribute('uv',new THREE.Float32BufferAttribute(data.uvs,2));geometry.setIndex(data.indices);geometry.computeBoundingSphere();const existing=chunks.get(key);if(existing){existing.geometry.dispose();existing.geometry=geometry;}else{const mesh=new THREE.Mesh(geometry,material);scene.add(mesh);chunks.set(key,mesh);}world.dirty.delete(key);}}
    function save(){try{localStorage.setItem(SAVE,JSON.stringify({version:BLOCK_SAVE_VERSION,edits:[...world.edits]}));if(!disposed)setSaved('Construcción guardada en este dispositivo');}catch{if(!disposed)setSaved('No se ha podido guardar: el espacio local está lleno o desactivado');}}
    function resized(){const rect=element!.getBoundingClientRect();width=Math.max(1,Math.floor(rect.width));height=Math.max(1,Math.floor(rect.height));renderer.setSize(width,height,false);}
    const observer=new ResizeObserver(resized);observer.observe(element);resized();
    const map:Record<string,[number,number]>={KeyA:[0,1],KeyD:[0,2],KeyW:[0,128],KeyS:[0,256],Space:[0,4],KeyF:[0,8],KeyG:[0,16],KeyE:[0,32],KeyR:[0,64],ArrowLeft:[1,1],ArrowRight:[1,2],ArrowUp:[1,128],ArrowDown:[1,256],ShiftRight:[1,4],KeyN:[1,8],KeyM:[1,16],KeyU:[1,32],KeyO:[1,64]};const lookKeys=new Set<string>();
    const down=(e:KeyboardEvent)=>{if(e.target instanceof HTMLElement&&e.target.closest('button,a,input,select,textarea'))return;const key=map[e.code];if(key){e.preventDefault();keys.current[key[0]]|=key[1];}if(['KeyI','KeyJ','KeyK','KeyL'].includes(e.code)){e.preventDefault();lookKeys.add(e.code);}if(e.code==='KeyP'&&!e.repeat)setPaused(v=>!v);};
    const up=(e:KeyboardEvent)=>{const key=map[e.code];if(key){e.preventDefault();keys.current[key[0]]&=~key[1];}lookKeys.delete(e.code);};
    let drag:{id:number;x:number;y:number}|null=null;
    const pointerDown=(e:PointerEvent)=>{if(helpRef.current||pause.current)return;element!.focus();const rect=element!.getBoundingClientRect();active=width>=height?(e.clientX-rect.left>width/2?1:0):(e.clientY-rect.top>height/2?1:0);if(e.pointerType==='mouse'){if(document.pointerLockElement!==element){void element!.requestPointerLock()?.catch(()=>{});}else keys.current[active]|=e.button===2?16:8;}else{element!.setPointerCapture(e.pointerId);drag={id:e.pointerId,x:e.clientX,y:e.clientY};}};
    const pointerUp=()=>{keys.current[0]&=~24;keys.current[1]&=~24;drag=null;};
    const move=(e:PointerEvent)=>{if(helpRef.current||pause.current)return;if(document.pointerLockElement===element)lookBuilder(players[active],e.movementX*.0027,e.movementY*.0027);else if(drag&&drag.id===e.pointerId){lookBuilder(players[active],(e.clientX-drag.x)*.006,(e.clientY-drag.y)*.006);drag.x=e.clientX;drag.y=e.clientY;}};
    const context=(e:Event)=>e.preventDefault();const blur=()=>{keys.current=[0,0];touch.current=0;lookKeys.clear();drag=null;if(document.hidden)setPaused(true);};
    const contextLost=(e:Event)=>{e.preventDefault();setError('La señal 3D se ha interrumpido. Tu última construcción guardada sigue en este dispositivo. Reabre el juego.');pause.current=true;};
    window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);window.addEventListener('pointerup',pointerUp);document.addEventListener('visibilitychange',blur);element.addEventListener('pointerdown',pointerDown);element.addEventListener('pointermove',move);element.addEventListener('pointercancel',pointerUp);element.addEventListener('contextmenu',context);element.addEventListener('webglcontextlost',contextLost);
    function draw(now:number){
      if(disposed)return;probe(now);const elapsed=Math.min(.05,(now-last)/1000);last=now;atmosphere.update(now/1000,reduced);
      for(const slot of[0,1]){const value=selections.current[slot];if(value!==null){players[slot].material=value;selections.current[slot]=null;}}
      if(!pause.current&&!helpRef.current&&!document.hidden){accumulator+=elapsed;while(accumulator>=1/90){for(const slot of[0,1]){const input=keys.current[slot]|(slot===0?touch.current:0)|consumeInput(remote.current[slot],now);const look=activeLook(remote.current[slot],now);if(slot){look[0]+=(lookKeys.has('KeyL')?1:0)-(lookKeys.has('KeyJ')?1:0);look[1]+=(lookKeys.has('KeyK')?1:0)-(lookKeys.has('KeyI')?1:0);}stepBuilder(world,players[slot],input,look,1/90);if(editFromBuilder(world,players,slot,input)){playArcadeSound(input&8?'break':'build');clearTimeout(saveTimer);saveTimer=setTimeout(save,700);}}accumulator-=1/90;}}else accumulator=0;
      if(world.dirty.size)remesh();
      for(const[slot,p]of players.entries()){avatars[slot].update(p,now/1000,reduced);lamps[slot].position.set(p.x,p.y+1.5,p.z);const hit=raycastBlocks(world,p);outlines[slot].visible=!!hit;if(hit)outlines[slot].position.set(hit.x+.5,hit.y+.5,hit.z+.5);}
      for(const slot of[0,1]){const p=players[slot],camera=cameras[slot];const wide=width>=height;const vw=wide?Math.floor(width/2):width,vh=wide?height:Math.floor(height/2),vx=wide?slot*vw:0,vy=wide?0:(1-slot)*vh;camera.aspect=vw/vh;camera.updateProjectionMatrix();camera.position.set(p.x,p.y+1.55,p.z);camera.rotation.set(p.pitch,p.yaw,0);avatars[slot].group.visible=false;avatars[1-slot].group.visible=true;outlines[1-slot].visible=false;const hit=raycastBlocks(world,p);outlines[slot].visible=!!hit;renderer.setViewport(vx,vy,vw,vh);renderer.setScissor(vx,vy,vw,vh);renderer.render(scene,camera);}
      if(now-lastHud>200){setMaterials(players.map(p=>p.material));setCoordinates(players.map(p=>`${Math.floor(p.x)} / ${Math.floor(p.y)} / ${Math.floor(p.z)}${p.flying?' · VUELO':''}`));lastHud=now;}frame=requestAnimationFrame(draw);
    }
    const loader=new THREE.TextureLoader();let texture:THREE.Texture|undefined;
    loader.load('/arcade/blocks-atlas-v2.webp',loaded=>{texture=loaded;if(disposed){loaded.dispose();return;}loaded.colorSpace=THREE.SRGBColorSpace;loaded.magFilter=THREE.NearestFilter;loaded.minFilter=THREE.LinearMipmapLinearFilter;loaded.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());material.map=loaded;material.needsUpdate=true;const total=world.dirty.size;function prepare(){if(disposed)return;remesh(4);setProgress(Math.round((1-world.dirty.size/total)*100));if(world.dirty.size)prepareTimer=setTimeout(prepare,16);else{setLoading(false);last=performance.now();frame=requestAnimationFrame(draw);recordArcade('blocks:ready');}}prepareTimer=setTimeout(prepare,0);},undefined,()=>{if(!disposed){setError('No se han podido cargar las texturas. Reabre el juego cuando tengas conexión.');setLoading(false);}});
    return()=>{disposed=true;cancelAnimationFrame(frame);clearTimeout(saveTimer);clearTimeout(prepareTimer);if(world.edits.size)save();observer.disconnect();if(document.pointerLockElement===element)document.exitPointerLock();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);window.removeEventListener('pointerup',pointerUp);document.removeEventListener('visibilitychange',blur);element.removeEventListener('pointerdown',pointerDown);element.removeEventListener('pointermove',move);element.removeEventListener('pointercancel',pointerUp);element.removeEventListener('contextmenu',context);element.removeEventListener('webglcontextlost',contextLost);const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>();scene.traverse(object=>{if(object instanceof THREE.Mesh||object instanceof THREE.LineSegments){geometries.add(object.geometry);(Array.isArray(object.material)?object.material:[object.material]).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());texture?.dispose();renderer.dispose();/* Do not force context loss: Strict Mode reuses this canvas for the next setup. */};
  },[remote]);
  const bind=(bit:number)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);touch.current|=bit;},onPointerUp:()=>{touch.current&=~bit;},onPointerCancel:()=>{touch.current&=~bit;},onLostPointerCapture:()=>{touch.current&=~bit;}});
  return <div className={styles.blocks}><canvas ref={canvas} className={styles.blockCanvas} tabIndex={0} aria-label="Isla libre. Mundo creativo compartido por dos jugadores. Usa los mandos QR o abre las instrucciones de teclado."/><div className={styles.splitDivider}/><div className={styles.blockReticle} data-player="0">+</div><div className={styles.blockReticle} data-player="1">+</div><div className={styles.blockHud}>{materials.map((material,slot)=><span key={slot}><b>J{slot+1} · {BLOCK_NAMES[material]}</b><small>{coordinates[slot]}</small><select aria-label={`Material jugador ${slot+1}`} value={material} onChange={e=>{selections.current[slot]=Number(e.target.value);}}>{BLOCK_NAMES.slice(1).map((name,index)=><option value={index+1} key={name}>{name}</option>)}</select><i style={{background:BLOCK_COLORS[material]}}/></span>)}</div><div className={styles.blockStatus}>{saved}<br/>ARCHIPIÉLAGO · 128 × 128 · 16 MATERIALES</div><div className={styles.gameActions}><button className={styles.button} onClick={()=>setHelp(true)}>Controles</button><button className={styles.button} onClick={()=>setPaused(p=>!p)}>{paused?'Continuar':'Pausa'}</button></div>
    <div className={styles.blockTouch}>{[[1,'←'],[128,'↑'],[256,'↓'],[2,'→'],[4,'Salta'],[8,'Rompe'],[16,'Pon'],[32,'Material'],[64,'Vuela']].map(([bit,label])=><button key={bit} {...bind(Number(bit))}>{label}</button>)}</div>
    {(loading||help||error||paused)&&<div className={styles.gameIntro}><small>ISLA LIBRE / ARCHIPIÉLAGO CREATIVO</small><h3>{error?'No hay señal 3D.':paused?'El mundo os espera.':'Más allá del horizonte.'}</h3><p>{error|| (loading?`Levantando montañas, cuevas y bosques… ${progress}%`:'Explorad montañas nevadas, playas y cuevas. Construid con 16 materiales y encontrad ruinas entre los árboles. Sin enemigos ni reloj. Guardado local independiente del mundo anterior.')}</p>{!loading&&!error&&<><div className={styles.blockInstructions}><p><b>J1</b> WASD · Ratón para mirar · ESPACIO salta · F/G rompe/coloca · E material · R vuelo.</p><p><b>J2</b> Flechas · IJKL para mirar · SHIFT derecho salta · N/M rompe/coloca · U material · O vuelo.</p><p>Con dos mandos QR jugáis a la vez. Salto asciende en vuelo; desactiva vuelo para bajar. El selector de cada jugador da acceso directo a los materiales. Escape libera el ratón.</p></div><button className={styles.button} onClick={()=>{setHelp(false);setPaused(false);canvas.current?.focus();}}>Entrar en la isla →</button></>}</div>}
  </div>;
}
