'use client';
import {useEffect,useRef,useState,type MutableRefObject} from 'react';
import * as THREE from 'three';
import {consumeInput,activeLook,type RemoteInput} from '@/lib/arcade-peer';
import {BLOCK_NAMES,blockChunkGeometry,editFromBuilder,newBlockWorld,newBuilder,restoreBlockEdits,stepBuilder,lookBuilder,raycastBlocks} from '@/lib/blocks-engine';
import styles from './Arcade.module.css';
import{arcadeFrameProbe,recordArcade}from'@/lib/arcade-diagnostics';
const SAVE='latech-isla-libre-v1';
export default function BlocksGame({remote,pauseSignal=0}:{remote:MutableRefObject<[RemoteInput,RemoteInput]>;pauseSignal?:number}){
  const canvas=useRef<HTMLCanvasElement>(null);const keys=useRef<[number,number]>([0,0]);const touch=useRef(0);const pause=useRef(false);
  const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[paused,setPaused]=useState(false);const[materials,setMaterials]=useState(['Hierba','Madera']);const[saved,setSaved]=useState('Se guarda en este dispositivo');const[help,setHelp]=useState(true);const helpRef=useRef(true);
  useEffect(()=>{pause.current=paused;},[paused]);useEffect(()=>{helpRef.current=help;},[help]);
  const previousPause=useRef(pauseSignal);useEffect(()=>{if(previousPause.current!==pauseSignal)setPaused(true);previousPause.current=pauseSignal;},[pauseSignal]);
  useEffect(()=>{
    const element=canvas.current;if(!element)return;let renderer:THREE.WebGLRenderer;let cancelled=false;
    try{renderer=new THREE.WebGLRenderer({canvas:element,antialias:false,powerPreference:'low-power'});}catch{recordArcade('blocks:webgl-unavailable');queueMicrotask(()=>{if(!cancelled){setError('Este dispositivo no ha podido iniciar los gráficos 3D. Los juegos 2D siguen disponibles.');setLoading(false);}});return()=>{cancelled=true;};}
    let disposed=false,frame=0,last=performance.now(),accumulator=0,lastHud=0,saveTimer:ReturnType<typeof setTimeout>|undefined,width=1,height=1,active=0;const probe=arcadeFrameProbe('blocks');
    const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
    const world=newBlockWorld();try{const raw=localStorage.getItem(SAVE);if(raw)restoreBlockEdits(world,raw);}catch{queueMicrotask(()=>{if(!disposed)setSaved('Guardado local no disponible');});}
    const players=[newBuilder(world,0),newBuilder(world,1)];const scene=new THREE.Scene();scene.background=new THREE.Color('#acdceb');scene.fog=new THREE.Fog('#acdceb',32,80);
    renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.setScissorTest(true);renderer.outputColorSpace=THREE.SRGBColorSpace;
    const cameras=[new THREE.PerspectiveCamera(72,1,.08,130),new THREE.PerspectiveCamera(72,1,.08,130)];cameras.forEach(c=>{c.rotation.order='YXZ';});
    const chunks=new Map<string,THREE.Mesh>();const material=new THREE.MeshBasicMaterial({vertexColors:true});
    const water=new THREE.Mesh(new THREE.PlaneGeometry(150,150),new THREE.MeshBasicMaterial({color:'#48afc8'}));water.rotation.x=-Math.PI/2;water.position.set(24,1.15,24);scene.add(water);
    const sun=new THREE.Mesh(new THREE.SphereGeometry(5,16,12),new THREE.MeshBasicMaterial({color:'#fff3ba',fog:false}));sun.position.set(-55,45,-75);scene.add(sun);
    scene.add(new THREE.HemisphereLight('#f0fcff','#aab3a0',2));
    const clouds=new THREE.Group();for(let n=0;n<8;n++){const cloud=new THREE.Mesh(new THREE.BoxGeometry(5+n%3,1.2,3),new THREE.MeshBasicMaterial({color:'#f2faff'}));cloud.position.set(n*12-22,19+n%3,-12+(n%3)*22);clouds.add(cloud);}scene.add(clouds);
    const avatars=players.map((_,slot)=>{const group=new THREE.Group();const color=slot?'#ef934b':'#248ac4';const body=new THREE.Mesh(new THREE.BoxGeometry(.48,.75,.3),new THREE.MeshLambertMaterial({color}));body.position.y=.88;const head=new THREE.Mesh(new THREE.BoxGeometry(.4,.4,.4),new THREE.MeshLambertMaterial({color:'#f4d6a4'}));head.position.y=1.46;group.add(body,head);for(const x of[-.14,.14]){const leg=new THREE.Mesh(new THREE.BoxGeometry(.18,.5,.2),new THREE.MeshLambertMaterial({color:'#173042'}));leg.position.set(x,.28,0);group.add(leg);}scene.add(group);return group;});
    const outlines=[0,1].map(slot=>{const box=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(1.007,1.007,1.007)),new THREE.LineBasicMaterial({color:slot?'#ffbb63':'#ffffff'}));scene.add(box);return box;});
    const leaves=new THREE.InstancedMesh(new THREE.PlaneGeometry(.13,.24),new THREE.MeshBasicMaterial({color:'#d0cd56',side:THREE.DoubleSide}),18);scene.add(leaves);const dummy=new THREE.Object3D();
    function remesh(){for(const key of world.dirty){const[cx,cz]=key.split(',').map(Number),data=blockChunkGeometry(world,cx,cz);const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(data.positions,3));geometry.setAttribute('normal',new THREE.Float32BufferAttribute(data.normals,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(data.colors,3));geometry.setAttribute('uv',new THREE.Float32BufferAttribute(data.uvs,2));geometry.setIndex(data.indices);geometry.computeBoundingSphere();const existing=chunks.get(key);if(existing){existing.geometry.dispose();existing.geometry=geometry;}else{const mesh=new THREE.Mesh(geometry,material);scene.add(mesh);chunks.set(key,mesh);}}world.dirty.clear();}
    function save(){try{localStorage.setItem(SAVE,JSON.stringify({version:1,edits:[...world.edits]}));setSaved('Construcción guardada en este dispositivo');}catch{setSaved('No se ha podido guardar: el espacio local está lleno o desactivado');}}
    function resized(){const rect=element!.getBoundingClientRect();width=Math.max(1,Math.floor(rect.width));height=Math.max(1,Math.floor(rect.height));renderer.setSize(width,height,false);}
    const observer=new ResizeObserver(resized);observer.observe(element);resized();
    const map:Record<string,[number,number]>={KeyA:[0,1],KeyD:[0,2],KeyW:[0,128],KeyS:[0,256],Space:[0,4],KeyF:[0,8],KeyG:[0,16],KeyE:[0,32],KeyR:[0,64],ArrowLeft:[1,1],ArrowRight:[1,2],ArrowUp:[1,128],ArrowDown:[1,256],ShiftRight:[1,4],KeyN:[1,8],KeyM:[1,16],KeyU:[1,32],KeyO:[1,64]};const lookKeys=new Set<string>();
    const down=(e:KeyboardEvent)=>{if(e.target instanceof HTMLElement&&e.target.closest('button,a,input,textarea'))return;const key=map[e.code];if(key){e.preventDefault();keys.current[key[0]]|=key[1];}if(['KeyI','KeyJ','KeyK','KeyL'].includes(e.code)){e.preventDefault();lookKeys.add(e.code);}if(e.code==='KeyP'&&!e.repeat)setPaused(v=>!v);};
    const up=(e:KeyboardEvent)=>{const key=map[e.code];if(key){e.preventDefault();keys.current[key[0]]&=~key[1];}lookKeys.delete(e.code);};
    let drag:{id:number;x:number;y:number}|null=null;
    const pointerDown=(e:PointerEvent)=>{if(helpRef.current||pause.current)return;element!.focus();const rect=element!.getBoundingClientRect();active=width>=height?(e.clientX-rect.left>width/2?1:0):(e.clientY-rect.top>height/2?1:0);if(e.pointerType==='mouse'){if(document.pointerLockElement!==element){void element!.requestPointerLock()?.catch(()=>{});}else keys.current[active]|=e.button===2?16:8;}else{element!.setPointerCapture(e.pointerId);drag={id:e.pointerId,x:e.clientX,y:e.clientY};}};
    const pointerUp=()=>{keys.current[0]&=~24;keys.current[1]&=~24;drag=null;};
    const move=(e:PointerEvent)=>{if(helpRef.current||pause.current)return;if(document.pointerLockElement===element)lookBuilder(players[active],e.movementX*.0027,e.movementY*.0027);else if(drag&&drag.id===e.pointerId){lookBuilder(players[active],(e.clientX-drag.x)*.006,(e.clientY-drag.y)*.006);drag.x=e.clientX;drag.y=e.clientY;}};
    const context=(e:Event)=>e.preventDefault();const blur=()=>{keys.current=[0,0];touch.current=0;lookKeys.clear();drag=null;if(document.hidden)setPaused(true);};
    const contextLost=(e:Event)=>{e.preventDefault();setError('La señal 3D se ha interrumpido. Tu última construcción guardada sigue en este dispositivo. Reabre el juego.');pause.current=true;};
    window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);window.addEventListener('pointerup',pointerUp);document.addEventListener('visibilitychange',blur);element.addEventListener('pointerdown',pointerDown);element.addEventListener('pointermove',move);element.addEventListener('pointercancel',pointerUp);element.addEventListener('contextmenu',context);element.addEventListener('webglcontextlost',contextLost);
    function draw(now:number){
      if(disposed)return;probe(now);const elapsed=Math.min(.05,(now-last)/1000);last=now;if(!reduced)clouds.position.x=Math.sin(now*.000025)*4;
      if(!pause.current&&!helpRef.current&&!document.hidden){accumulator+=elapsed;while(accumulator>=1/90){for(const slot of[0,1]){const input=keys.current[slot]|(slot===0?touch.current:0)|consumeInput(remote.current[slot],now);const look=activeLook(remote.current[slot],now);if(slot){look[0]+=(lookKeys.has('KeyL')?1:0)-(lookKeys.has('KeyJ')?1:0);look[1]+=(lookKeys.has('KeyK')?1:0)-(lookKeys.has('KeyI')?1:0);}stepBuilder(world,players[slot],input,look,1/90);if(editFromBuilder(world,players,slot,input)){clearTimeout(saveTimer);saveTimer=setTimeout(save,700);}}accumulator-=1/90;}}else accumulator=0;
      if(world.dirty.size)remesh();
      for(let n=0;n<18;n++){dummy.position.set(10+(n*7)%31+Math.sin((reduced?0:now*.0004)+n)*2,4+((n*1.7-(reduced?0:now*.0006))%9+9)%9,8+(n*11)%34);dummy.rotation.set(n+(reduced?0:now*.0005),n,0);dummy.updateMatrix();leaves.setMatrixAt(n,dummy.matrix);}leaves.instanceMatrix.needsUpdate=true;
      for(const[slot,p]of players.entries()){avatars[slot].position.set(p.x,p.y,p.z);avatars[slot].rotation.y=p.yaw;if(!reduced)avatars[slot].children[1].position.y=1.46+Math.sin(now*.003+slot)*.012;const hit=raycastBlocks(world,p);outlines[slot].visible=!!hit;if(hit)outlines[slot].position.set(hit.x+.5,hit.y+.5,hit.z+.5);}
      for(const slot of[0,1]){const p=players[slot],camera=cameras[slot];const wide=width>=height;const vw=wide?Math.floor(width/2):width,vh=wide?height:Math.floor(height/2),vx=wide?slot*vw:0,vy=wide?0:(1-slot)*vh;camera.aspect=vw/vh;camera.updateProjectionMatrix();camera.position.set(p.x,p.y+1.55,p.z);camera.rotation.set(p.pitch,p.yaw,0);avatars[slot].visible=false;avatars[1-slot].visible=true;outlines[1-slot].visible=false;const hit=raycastBlocks(world,p);outlines[slot].visible=!!hit;renderer.setViewport(vx,vy,vw,vh);renderer.setScissor(vx,vy,vw,vh);renderer.render(scene,camera);}
      if(now-lastHud>200){setMaterials(players.map(p=>`${BLOCK_NAMES[p.material]}${p.flying?' · VUELO':''}`));lastHud=now;}frame=requestAnimationFrame(draw);
    }
    const loader=new THREE.TextureLoader();let texture:THREE.Texture|undefined;
    loader.load('/arcade/blocks-textures.webp',loaded=>{texture=loaded;if(disposed){loaded.dispose();return;}loaded.colorSpace=THREE.SRGBColorSpace;loaded.magFilter=THREE.NearestFilter;loaded.minFilter=THREE.LinearMipmapLinearFilter;loaded.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());material.map=loaded;material.needsUpdate=true;remesh();setLoading(false);last=performance.now();frame=requestAnimationFrame(draw);},undefined,()=>{if(!disposed){setError('No se han podido cargar las texturas. Reabre el juego cuando tengas conexión.');setLoading(false);}});
    return()=>{disposed=true;cancelAnimationFrame(frame);clearTimeout(saveTimer);if(world.edits.size)save();observer.disconnect();if(document.pointerLockElement===element)document.exitPointerLock();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);window.removeEventListener('pointerup',pointerUp);document.removeEventListener('visibilitychange',blur);element.removeEventListener('pointerdown',pointerDown);element.removeEventListener('pointermove',move);element.removeEventListener('pointercancel',pointerUp);element.removeEventListener('contextmenu',context);element.removeEventListener('webglcontextlost',contextLost);const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>();scene.traverse(object=>{if(object instanceof THREE.Mesh||object instanceof THREE.LineSegments){geometries.add(object.geometry);(Array.isArray(object.material)?object.material:[object.material]).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());texture?.dispose();renderer.dispose();/* Do not force context loss: Strict Mode reuses this canvas for the next setup. */};
  },[remote]);
  const bind=(bit:number)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);touch.current|=bit;},onPointerUp:()=>{touch.current&=~bit;},onPointerCancel:()=>{touch.current&=~bit;},onLostPointerCapture:()=>{touch.current&=~bit;}});
  return <div className={styles.blocks}><canvas ref={canvas} className={styles.blockCanvas} tabIndex={0} aria-label="Isla libre. Mundo creativo compartido por dos jugadores. Usa los mandos QR o abre las instrucciones de teclado."/><div className={styles.splitDivider}/><div className={styles.blockReticle} data-player="0">+</div><div className={styles.blockReticle} data-player="1">+</div><div className={styles.blockHud}>{materials.map((name,slot)=><span key={slot}>J{slot+1} · {name}</span>)}</div><div className={styles.blockStatus}>{saved}</div><div className={styles.gameActions}><button className={styles.button} onClick={()=>setHelp(true)}>Controles</button><button className={styles.button} onClick={()=>setPaused(p=>!p)}>{paused?'Continuar':'Pausa'}</button></div>
    <div className={styles.blockTouch}>{[[1,'←'],[128,'↑'],[256,'↓'],[2,'→'],[4,'Salta'],[8,'Rompe'],[16,'Pon'],[32,'Material']].map(([bit,label])=><button key={bit} {...bind(Number(bit))}>{label}</button>)}</div>
    {(loading||help||error||paused)&&<div className={styles.gameIntro}><small>ISLA LIBRE / CREATIVO COOPERATIVO</small><h3>{error?'No hay señal 3D.':paused?'El mundo os espera.':'Un mundo. Dos ideas.'}</h3><p>{error|| (loading?'Preparando la isla y sus materiales…':'Construid juntos, sin enemigos ni reloj. Romped, colocad, saltad o volad. Las construcciones se guardan en este dispositivo.')}</p>{!loading&&!error&&<><div className={styles.blockInstructions}><p><b>J1</b> WASD · Ratón para mirar · ESPACIO salta · F/G rompe/coloca · E material · R vuelo.</p><p><b>J2</b> Flechas · IJKL para mirar · SHIFT derecho salta · N/M rompe/coloca · U material · O vuelo.</p><p>O conecta dos mandos QR. En vuelo, salto asciende; desactiva vuelo para bajar. Haz clic en una mitad para controlarla con el ratón; Escape lo libera.</p></div><button className={styles.button} onClick={()=>{setHelp(false);setPaused(false);canvas.current?.focus();}}>Entrar en la isla →</button></>}</div>}
  </div>;
}
