'use client';
/* eslint-disable @next/next/no-img-element -- Temporary in-memory photo preview. */
import{useEffect,useRef,useState}from'react';
import styles from './Arcade.module.css';
export default function TvPhotoCapture({sendPhoto,disabled}:{sendPhoto:(blob:Blob)=>Promise<void>;disabled:boolean}){
  const input=useRef<HTMLInputElement>(null);const[blob,setBlob]=useState<Blob|null>(null);const[preview,setPreview]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
  async function load(file:File|undefined){if(!file)return;setMessage('');setBusy(true);try{if(file.size>20_000_000)throw new Error('Elige una foto de menos de 20 MB.');const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,1280/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('No se ha podido preparar la foto.');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const image=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.8));if(!image||image.size>500_000)throw new Error('Esta foto es demasiado compleja. Prueba con otra más pequeña.');setBlob(image);setPreview(URL.createObjectURL(image));}finally{bitmap.close();}}catch(cause){setMessage(cause instanceof Error?cause.message:'No se reconoce esta foto. Prueba con JPG o PNG.');}finally{setBusy(false);}}
  async function send(){if(!blob||busy)return;setBusy(true);try{await sendPhoto(blob);setMessage('Enviada a la televisión. Se mostrará durante 60 segundos.');}catch(cause){setMessage(cause instanceof Error?cause.message:'No se ha podido enviar la foto.');}finally{setBusy(false);}}
  return <section className={styles.photoCapture}><h2>Tu momento.<br/>Nuestra pantalla.</h2><p>Haz una foto y muéstrala en esta televisión durante 60 segundos. Solo se envía cuando pulses el botón; no se guarda en el servidor ni se publica en redes.</p><input ref={input} type="file" accept="image/*" capture="environment" hidden onChange={event=>{void load(event.target.files?.[0]);event.target.value='';}}/>{preview&&<img src={preview} alt="Vista previa de la foto que vas a mostrar"/>}<button className={styles.button} disabled={busy} onClick={()=>input.current?.click()}>{busy?'Preparando…':blob?'Hacer otra foto':'Abrir cámara'}</button>{blob&&<button className={styles.button} disabled={busy||disabled} onClick={()=>void send()}>Mostrar en la tele · 60 s</button>}<p role="status">{message|| (disabled?'Esperando la señal directa…':'La televisión está lista.')}</p></section>;
}
