import {describe,it} from 'node:test';
import assert from 'node:assert/strict';
import {newFightWorld,stepFight,FIGHT_FLOOR} from '../src/lib/fight-engine';
import {newBlockWorld,newBuilder,setBlock,getBlock,stepBuilder,lookBuilder,raycastBlocks,editFromBuilder,restoreBlockEdits,blockChunkGeometry,blockIndex,BLOCK_NAMES,BLOCK_SIZE,BLOCK_HEIGHT,BLOCK_SAVE_VERSION} from '../src/lib/blocks-engine';
describe('Neon Clash combat',()=>{
  function playing(){const w=newFightWorld();for(let n=0;n<160;n++)stepFight(w,[0,0],1/120);assert.equal(w.phase,'playing');return w;}
  it('requires an intro, keeps attacks in range and applies only one hit',()=>{const w=playing();w.fighters[1].x=w.fighters[0].x+80;for(let i=0;i<90;i++)stepFight(w,[8,0],1/120);assert.equal(w.fighters[1].health,93);const far=playing();for(let i=0;i<90;i++)stepFight(far,[8,0],1/120);assert.equal(far.fighters[1].health,100);});
  it('sustained blocks reduce damage and specials require energy',()=>{const w=playing();w.fighters[1].x=w.fighters[0].x+80;for(let i=0;i<30;i++)stepFight(w,[0,32],1/120);for(let i=0;i<90;i++)stepFight(w,[8,32],1/120);assert.equal(w.fighters[1].health,98);const no=playing();stepFight(no,[64,0],1/120);assert.equal(no.fighters[0].move,'idle');const yes=playing();yes.fighters[0].energy=100;for(let i=0;i<34;i++)stepFight(yes,[64,0],1/120);assert.equal(yes.fighters[0].energy,40);assert.equal(yes.projectiles.length,1);});
  it('rewards a timely defence with a parry for either player',()=>{for(const defender of[0,1]as const){const w=playing();w.fighters[1].x=w.fighters[0].x+80;const input:[number,number]=defender===0?[32,8]:[8,32];for(let i=0;i<30;i++)stepFight(w,input,1/120);assert.equal(w.fighters[defender].health,100);assert.equal(w.parries,1);assert.equal(w.notice,'DEFENSA PERFECTA');}});
  it('breaks depleted guard, and a held dash cannot retrigger',()=>{const w=playing();w.fighters[1].x=w.fighters[0].x+80;for(let i=0;i<30;i++)stepFight(w,[0,32],1/120);w.fighters[1].guard=5;for(let i=0;i<20;i++)stepFight(w,[8,32],1/120);assert.equal(w.fighters[1].health,93);assert.ok(w.fighters[1].guardLock>0);const dash=playing();stepFight(dash,[128,0],1/120);assert.ok(dash.fighters[0].dash>0);for(let i=0;i<160;i++)stepFight(dash,[128,0],1/120);assert.equal(dash.fighters[0].dash,0);stepFight(dash,[0,0],1/120);stepFight(dash,[128,0],1/120);assert.ok(dash.fighters[0].dash>0);});
  it('links a confirmed punch into a kick without waiting for recovery',()=>{const w=playing();w.fighters[1].x=w.fighters[0].x+80;for(let i=0;i<25;i++)stepFight(w,[8,0],1/120);assert.equal(w.fighters[1].health,93);stepFight(w,[16,0],1/120);assert.equal(w.fighters[0].move,'kick');});
  it('has jumps, two-round victories and clean round resets',()=>{const w=playing();stepFight(w,[4,0],1/120);assert.ok(w.fighters[0].y<FIGHT_FLOOR);w.fighters[1].health=0;stepFight(w,[0,0],1/120);assert.equal(w.wins[0],1);for(let i=0;i<410;i++)stepFight(w,[0,0],1/120);assert.equal(w.round,2);assert.equal(w.fighters[1].health,100);w.fighters[1].health=0;stepFight(w,[0,0],1/120);assert.equal(w.phase,'complete');assert.equal(w.winner,0);});
});
describe('Isla libre shared world',()=>{
  it('generates deterministic, bounded material data with larger depth',()=>{const a=newBlockWorld(),b=newBlockWorld();assert.deepEqual(a.cells,b.cells);assert.equal(a.cells.length,128*128*64);assert.equal(BLOCK_SIZE,128);assert.equal(BLOCK_HEIGHT,64);assert.ok(a.cells.every(v=>v>=0&&v<BLOCK_NAMES.length));assert.ok(new Set(a.cells).size>=14);assert.equal(setBlock(a,-1,4,3,1),false);assert.equal(setBlock(a,1,0,1,0),false);assert.equal(setBlock(a,1,4,1,17),false);});
  it('edits one shared world and dirties both sides of a chunk border',()=>{const w=newBlockWorld();w.dirty.clear();assert.equal(setBlock(w,15,55,15,4),true);assert.equal(getBlock(w,15,55,15),4);assert.ok(w.dirty.has('0,0')&&w.dirty.has('1,0')&&w.dirty.has('0,1'));});
  it('saves and validates edits without accepting malformed or older worlds',()=>{const w=newBlockWorld();setBlock(w,20,55,20,16);const next=newBlockWorld();assert.equal(restoreBlockEdits(next,JSON.stringify({version:BLOCK_SAVE_VERSION,edits:[...w.edits]})),true);assert.deepEqual(next.cells,w.cells);assert.equal(restoreBlockEdits(next,JSON.stringify({version:BLOCK_SAVE_VERSION,edits:[[blockIndex(1,10,1),99]]})),false);assert.equal(restoreBlockEdits(next,JSON.stringify({version:1,edits:[]})),false);assert.equal(restoreBlockEdits(next,'null'),false);});
  it('lands, moves independently, jumps and limits look pitch',()=>{const w=newBlockWorld(),p=newBuilder(w,0),q=newBuilder(w,1);for(let i=0;i<60;i++)stepBuilder(w,p,0,[0,0],1/120);assert.equal(p.grounded,true);const y=p.y;stepBuilder(w,p,4,[0,0],1/120);assert.ok(p.y>y);const z=q.z;for(let i=0;i<30;i++)stepBuilder(w,p,128,[0,0],1/120);assert.equal(q.z,z);lookBuilder(p,0,999);assert.equal(p.pitch,-1.45);});
  it('raycasts exact cells, respects reach and cannot place inside players',()=>{const w=newBlockWorld(),p=newBuilder(w,0);w.cells.fill(0);Object.assign(p,{x:20.5,y:15,z:20.5,yaw:0,pitch:0});setBlock(w,20,16,17,3);const hit=raycastBlocks(w,p);assert.equal(hit?.z,17);assert.equal(raycastBlocks(w,p,1),null);assert.equal(editFromBuilder(w,[p],0,8),true);assert.equal(getBlock(w,20,16,17),0);setBlock(w,20,16,19,3);p.cooldown=0;assert.equal(editFromBuilder(w,[p],0,16),false);});
  it('culls internal faces and produces matching vertex attributes',()=>{const w=newBlockWorld();w.cells.fill(0);setBlock(w,1,5,1,3);setBlock(w,2,5,1,3);const g=blockChunkGeometry(w,0,0);assert.equal(g.indices.length,10*6);assert.equal(g.positions.length,g.normals.length);assert.equal(g.colors.length,g.positions.length);assert.equal(g.uvs.length,g.positions.length/3*2);assert.ok(g.uvs.every(v=>v>=0&&v<=1));});
});
