/**
 * AUTO-GENERATED by scripts/seed-stripe.ts. Do not edit manually.
 *
 * Estructura dual: los IDs de la cuenta Stripe TEST y la cuenta LIVE
 * conviven en este fichero. El cliente (lib/stripe.ts) detecta el
 * modo por el prefijo de STRIPE_SECRET_KEY (sk_test_ vs sk_live_) y
 * `getCurrentPrices()` devuelve la sección correcta.
 *
 * El script de seed solo sobrescribe la sección correspondiente al
 * modo en el que se ejecuta — la otra queda intacta.
 */

import type { CatalogId } from './catalog';

export type StripePriceMapping = {
  productId: string;
  priceId: string;
};

export type StripeMode = 'test' | 'live';

/**
 * Última actualización LIVE: 2026-05-02T04:30:23.083Z
 * Source: metadata.source = 'calculator_v1'
 */
const TEST_PRICES: Record<CatalogId, StripePriceMapping> = {
  webCreationLe8: { productId: 'prod_URHEst3fpsB6nt', priceId: 'price_1TSOgU2YFBctOmUDV8nQr0hz' },
  webCreationGt8: { productId: 'prod_URHE3vT9WbBjbJ', priceId: 'price_1TSOgU2YFBctOmUDMjrVncPZ' },
  hostingMonthly: { productId: 'prod_URHEoP1z1I4UX4', priceId: 'price_1TSOgV2YFBctOmUDyO3fdswA' },
  hostingYearly: { productId: 'prod_URHFzpEucndcGE', priceId: 'price_1TSOgW2YFBctOmUDkKEYyRZb' },
  tiendaMonthly: { productId: 'prod_URHFoXpbv26Ruu', priceId: 'price_1TSOgX2YFBctOmUDyuIxiswa' },
  tiendaYearlyWithHosting: { productId: 'prod_URHFbjue3F68cV', priceId: 'price_1TSOgY2YFBctOmUDhELbHoT3' },
  socialMedia: { productId: 'prod_URHFPu4HBrQV7X', priceId: 'price_1TSOgZ2YFBctOmUDBUnvCj3J' },
  socialMediaYearly: { productId: 'prod_URHFggCJGv8Fn1', priceId: 'price_1TSOga2YFBctOmUD04VrnFIV' },
  aiWeb: { productId: 'prod_URHFmADSU0YKPp', priceId: 'price_1TSOgb2YFBctOmUDsSzOePSE' },
  aiWebYearly: { productId: 'prod_URHFgI5Itk1KnP', priceId: 'price_1TSOgc2YFBctOmUDNo8HPcXI' },
  aiPhone: { productId: 'prod_URHF3FaUa321Cp', priceId: 'price_1TSOgd2YFBctOmUDBllcxJAt' },
  aiPhoneYearly: { productId: 'prod_URHFiOtjVZsHNg', priceId: 'price_1TSOge2YFBctOmUD6KZAgxhD' },
  blogPost: { productId: 'prod_URHFBgh1CzjdT1', priceId: 'price_1TSOgf2YFBctOmUDFBDkQbDI' },
  blogPostYearly: { productId: 'prod_URHFu4ZWcaZJDt', priceId: 'price_1TSOgg2YFBctOmUDbFevV3Yi' },
  logo: { productId: 'prod_URHF6BfKp6EZfb', priceId: 'price_1TSOgh2YFBctOmUDPaTLhHPp' },
  seoHour: { productId: 'prod_URHFF3qyV85kmh', priceId: 'price_1TSOgi2YFBctOmUDvUCER9t9' },
};

const LIVE_PRICES: Record<CatalogId, StripePriceMapping> = {
  webCreationLe8: { productId: 'prod_URNxEF3flH2gEw', priceId: 'price_1TSVBs2YFBctOmUDcVjkwlRX' },
  webCreationGt8: { productId: 'prod_URNx7gYNste3FI', priceId: 'price_1TSVBt2YFBctOmUDe3tqdK4Z' },
  hostingMonthly: { productId: 'prod_URNxO7vK0feLLh', priceId: 'price_1TSVBu2YFBctOmUDRk7rF1ue' },
  hostingYearly: { productId: 'prod_URNxHTJXrAqVNe', priceId: 'price_1TSVBv2YFBctOmUDbGZvas2x' },
  tiendaMonthly: { productId: 'prod_URNxxWoiuuzumw', priceId: 'price_1TSVBw2YFBctOmUDcsP8d3O6' },
  tiendaYearlyWithHosting: { productId: 'prod_URNxCT4LPpReQB', priceId: 'price_1TSVBx2YFBctOmUD1DYx3ApH' },
  socialMedia: { productId: 'prod_URNxxIRxJm5hdb', priceId: 'price_1TSVBy2YFBctOmUDeBAbEyD6' },
  socialMediaYearly: { productId: 'prod_URNxEQTD90GdEI', priceId: 'price_1TSVBz2YFBctOmUDm2QLJV3Q' },
  aiWeb: { productId: 'prod_URNxr41HlfKSjh', priceId: 'price_1TSVC02YFBctOmUDy5enrvnu' },
  aiWebYearly: { productId: 'prod_URNxNCdpDLlp8Z', priceId: 'price_1TSVC12YFBctOmUDmkvy44pF' },
  aiPhone: { productId: 'prod_URNxaeNdHGAhzj', priceId: 'price_1TSVC22YFBctOmUDN1lyA1vv' },
  aiPhoneYearly: { productId: 'prod_URNxuMS8zi5W2k', priceId: 'price_1TSVC32YFBctOmUDrrlmpeWf' },
  blogPost: { productId: 'prod_URNx8kPOnnXfZm', priceId: 'price_1TSVC42YFBctOmUDbZHVRbTe' },
  blogPostYearly: { productId: 'prod_URNyIRSzsvA43X', priceId: 'price_1TSVC52YFBctOmUDWAyD5Cbe' },
  logo: { productId: 'prod_URNyB0GcCG6isj', priceId: 'price_1TSVC52YFBctOmUDvgcXhOW6' },
  seoHour: { productId: 'prod_URNygHevyXgss8', priceId: 'price_1TSVC62YFBctOmUDwTlxzsV6' },
};

export const STRIPE_PRICES: Record<StripeMode, Record<CatalogId, StripePriceMapping>> = {
  test: TEST_PRICES,
  live: LIVE_PRICES,
};
