/**
 * AUTO-GENERATED by scripts/seed-stripe.ts. Do not edit manually.
 *
 * Estructura dual: los IDs de la cuenta Stripe TEST y la cuenta LIVE
 * conviven en este fichero. El cliente (lib/stripe.ts) detecta el
 * modo por el prefijo de STRIPE_SECRET_KEY (sk_test_ vs sk_live_) y
 * `getCurrentPrices()` devuelve la sección correcta.
 *
 * El script de seed solo sobrescribe la sección correspondiente al
 * modo en el que se ejecuta — la otra queda intacta.
 */

import type { CatalogId } from './catalog';

export type StripePriceMapping = {
  productId: string;
  priceId: string;
};

export type StripeMode = 'test' | 'live';

/**
 * Última actualización TEST: 2026-05-01T21:33:32.848Z
 * Source: metadata.source = 'calculator_v1'
 */
const TEST_PRICES: Record<CatalogId, StripePriceMapping> = {
  webCreationLe8: { productId: 'prod_URHEst3fpsB6nt', priceId: 'price_1TSOgU2YFBctOmUDV8nQr0hz' },
  webCreationGt8: { productId: 'prod_URHE3vT9WbBjbJ', priceId: 'price_1TSOgU2YFBctOmUDMjrVncPZ' },
  hostingMonthly: { productId: 'prod_URHEoP1z1I4UX4', priceId: 'price_1TSOgV2YFBctOmUDyO3fdswA' },
  hostingYearly: { productId: 'prod_URHFzpEucndcGE', priceId: 'price_1TSOgW2YFBctOmUDkKEYyRZb' },
  tiendaMonthly: { productId: 'prod_URHFoXpbv26Ruu', priceId: 'price_1TSOgX2YFBctOmUDyuIxiswa' },
  tiendaYearlyWithHosting: { productId: 'prod_URHFbjue3F68cV', priceId: 'price_1TSOgY2YFBctOmUDhELbHoT3' },
  socialMedia: { productId: 'prod_URHFPu4HBrQV7X', priceId: 'price_1TSOgZ2YFBctOmUDBUnvCj3J' },
  socialMediaYearly: { productId: 'prod_URHFggCJGv8Fn1', priceId: 'price_1TSOga2YFBctOmUD04VrnFIV' },
  aiWeb: { productId: 'prod_URHFmADSU0YKPp', priceId: 'price_1TSOgb2YFBctOmUDsSzOePSE' },
  aiWebYearly: { productId: 'prod_URHFgI5Itk1KnP', priceId: 'price_1TSOgc2YFBctOmUDNo8HPcXI' },
  aiPhone: { productId: 'prod_URHF3FaUa321Cp', priceId: 'price_1TSOgd2YFBctOmUDBllcxJAt' },
  aiPhoneYearly: { productId: 'prod_URHFiOtjVZsHNg', priceId: 'price_1TSOge2YFBctOmUD6KZAgxhD' },
  blogPost: { productId: 'prod_URHFBgh1CzjdT1', priceId: 'price_1TSOgf2YFBctOmUDFBDkQbDI' },
  blogPostYearly: { productId: 'prod_URHFu4ZWcaZJDt', priceId: 'price_1TSOgg2YFBctOmUDbFevV3Yi' },
  logo: { productId: 'prod_URHF6BfKp6EZfb', priceId: 'price_1TSOgh2YFBctOmUDPaTLhHPp' },
  seoHour: { productId: 'prod_URHFF3qyV85kmh', priceId: 'price_1TSOgi2YFBctOmUDvUCER9t9' },
};

/**
 * LIVE: vacío hasta ejecutar `npm run stripe:seed` con sk_live_*.
 * Mientras esté vacío, getCurrentPrices() en modo 'live' devuelve
 * placeholders y el código que use priceId fallará explícitamente al
 * llamar a Stripe — comportamiento intencional para no facturar mal.
 */
const LIVE_PRICES: Record<CatalogId, StripePriceMapping> = {
  webCreationLe8: { productId: '', priceId: '' },
  webCreationGt8: { productId: '', priceId: '' },
  hostingMonthly: { productId: '', priceId: '' },
  hostingYearly: { productId: '', priceId: '' },
  tiendaMonthly: { productId: '', priceId: '' },
  tiendaYearlyWithHosting: { productId: '', priceId: '' },
  socialMedia: { productId: '', priceId: '' },
  socialMediaYearly: { productId: '', priceId: '' },
  aiWeb: { productId: '', priceId: '' },
  aiWebYearly: { productId: '', priceId: '' },
  aiPhone: { productId: '', priceId: '' },
  aiPhoneYearly: { productId: '', priceId: '' },
  blogPost: { productId: '', priceId: '' },
  blogPostYearly: { productId: '', priceId: '' },
  logo: { productId: '', priceId: '' },
  seoHour: { productId: '', priceId: '' },
};

export const STRIPE_PRICES: Record<StripeMode, Record<CatalogId, StripePriceMapping>> = {
  test: TEST_PRICES,
  live: LIVE_PRICES,
};
